services:
  fhir:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      APP_MODULE: app.main_fhir:app
      HEADEASE_REDIS_URL: redis://redis:6379
      HEADEASE_HAPI_BASE_URL: http://hapi-fhir:8080/fhir
      HEADEASE_CLIENT_CERT: /certs/headease-certificates-proeftuin/headease-uzi-external-intermediate/headease-uzi-chain.crt
      HEADEASE_CLIENT_KEY: /certs/headease_nvi_20260202_145627.key
      HEADEASE_UZI_CERT: /certs/headease-certificates-proeftuin/headease-uzi-external-intermediate/headease-uzi.crt
      HEADEASE_UZI_INTERMEDIATE_CERT: /certs/gfmodules-test-uzi-external-intermediate.cer
      HEADEASE_LDN_CERT: /certs/headease-certificates-proeftuin/headease-ldn-external-intermediate/headease-ldn.crt
      HEADEASE_LDN_CHAIN_CERT: /certs/headease-certificates-proeftuin/headease-ldn-external-intermediate/headease-ldn-chain.crt
      HEADEASE_LDN_CA_CERT: /certs/headease-certificates-proeftuin/headease-ldn-external-intermediate/ldn-ca.crt
      HEADEASE_UZI_CA_CERT: /certs/headease-certificates-proeftuin/headease-uzi-external-intermediate/uzi-ca.crt
    volumes:
      - ./certificates:/certs:ro
    depends_on:
      - redis
      - hapi-fhir

  admin:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    env_file: .env
    environment:
      APP_MODULE: app.main_admin:app
      HEADEASE_REDIS_URL: redis://redis:6379
      HEADEASE_NK_HOST: nuts-knooppunt
      HEADEASE_CLIENT_CERT: /certs/headease-certificates-proeftuin/headease-uzi-external-intermediate/headease-uzi-chain.crt
      HEADEASE_CLIENT_KEY: /certs/headease_nvi_20260202_145627.key
      HEADEASE_UZI_CERT: /certs/headease-certificates-proeftuin/headease-uzi-external-intermediate/headease-uzi.crt
      HEADEASE_UZI_INTERMEDIATE_CERT: /certs/gfmodules-test-uzi-external-intermediate.cer
      HEADEASE_LDN_CERT: /certs/headease-certificates-proeftuin/headease-ldn-external-intermediate/headease-ldn.crt
      HEADEASE_LDN_CHAIN_CERT: /certs/headease-certificates-proeftuin/headease-ldn-external-intermediate/headease-ldn-chain.crt
      HEADEASE_LDN_CA_CERT: /certs/headease-certificates-proeftuin/headease-ldn-external-intermediate/ldn-ca.crt
      HEADEASE_UZI_CA_CERT: /certs/headease-certificates-proeftuin/headease-uzi-external-intermediate/uzi-ca.crt
    volumes:
      - ./certificates:/certs:ro
    depends_on:
      - redis
      - nuts-knooppunt

  nuts-knooppunt:
#    image: ghcr.io/nuts-foundation/nuts-knooppunt:0.11.0
    image: ghcr.io/nuts-foundation/nuts-knooppunt:nvi-delete-query-params
    ports:
      - "8080:8080"   # public
      - "8081:8081"   # internal
    environment:
      KNPT_STRICTMODE: "false"
      KNPT_HTTP_PUBLIC_ADDRESS: ":8080"
      KNPT_HTTP_INTERNAL_ADDRESS: ":8081"
      KNPT_AUTHN_MINVWS_TOKENENDPOINT: "https://oauth.proeftuin.gf.irealisatie.nl/oauth/token"
      KNPT_AUTHN_MINVWS_TLSCERTFILE: "/certs/headease-certificates-proeftuin/headease-uzi-external-intermediate/headease-uzi-chain.crt"
      KNPT_AUTHN_MINVWS_TLSKEYFILE: "/certs/headease_nvi_20260202_145627.key"
      KNPT_MCSD_ADMIN_ROOT_FHIRBASEURL: "https://adressering.proeftuin.gf.irealisatie.nl/poc/FHIR/fhir"
      KNPT_PSEUDO_PRSURL: "https://pseudoniemendienst.proeftuin.gf.irealisatie.nl"
      KNPT_NVI_BASEURL: "https://nvi.proeftuin.gf.irealisatie.nl/v1-poc/fhir"
      KNPT_NVI_AUDIENCE: "90000901"
    volumes:
      - ./certificates:/certs:ro

  hapi-fhir:
    image: hapiproject/hapi:latest
    ports:
      - "8082:8080"
    environment:
      hapi.fhir.server_id_strategy: UUID
      hapi.fhir.tester_enabled: "false"

  redis:
    image: redis:7-alpine
