{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "headease.fullname" . }}
  labels:
    {{- include "headease.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  tls:
    - hosts:
        - {{ .Values.ingress.fhirHost }}
        - {{ .Values.ingress.adminHost }}
      secretName: {{ include "headease.fullname" . }}-tls
  rules:
    - host: {{ .Values.ingress.fhirHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "headease.fullname" . }}-fhir
                port:
                  number: {{ .Values.service.port }}
    - host: {{ .Values.ingress.adminHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "headease.fullname" . }}-admin
                port:
                  number: {{ .Values.service.port }}
{{- end }}
