{{- if not .Values.certificates.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "headease.fullname" . }}-certs
  labels:
    {{- include "headease.labels" . | nindent 4 }}
type: Opaque
data:
  uzi.crt: {{ .Values.certificates.uziCert | quote }}
  uzi-chain.crt: {{ .Values.certificates.uziChainCert | quote }}
  uzi-intermediate.cer: {{ .Values.certificates.uziIntermediateCert | quote }}
  ldn.crt: {{ .Values.certificates.ldnCert | quote }}
  ldn-chain.crt: {{ .Values.certificates.ldnChainCert | quote }}
  private.key: {{ .Values.certificates.privateKey | quote }}
{{- end }}
